name: "Pull Request Checks"

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  pr-dependencies:
    runs-on: ubuntu-latest
    name: "Check PR Dependencies"
    steps:
      - name: PR Dependency Check
        uses: gregsdennis/dependencies-action@ae6e0529ef70f1366a21972f40b1ad0e1b5e3218 # v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  semantic-title:
    name: "Check Semantic Title"
    runs-on: ubuntu-latest
    steps:
      - name: "Check Semantic Pull Request"
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
